#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-proxy
Version  : 0.4.27
Release  : 56
URL      : https://cran.r-project.org/src/contrib/proxy_0.4-27.tar.gz
Source0  : https://cran.r-project.org/src/contrib/proxy_0.4-27.tar.gz
Summary  : Distance and Similarity Measures
Group    : Development/Tools
License  : GPL-2.0
Requires: R-proxy-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-proxy package.
Group: Libraries

%description lib
lib components for the R-proxy package.


%prep
%setup -q -n proxy
pushd ..
cp -a proxy buildavx2
popd
pushd ..
cp -a proxy buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737154023

%install
export SOURCE_DATE_EPOCH=1737154023
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/proxy/DESCRIPTION
/usr/lib64/R/library/proxy/INDEX
/usr/lib64/R/library/proxy/Meta/Rd.rds
/usr/lib64/R/library/proxy/Meta/features.rds
/usr/lib64/R/library/proxy/Meta/hsearch.rds
/usr/lib64/R/library/proxy/Meta/links.rds
/usr/lib64/R/library/proxy/Meta/nsInfo.rds
/usr/lib64/R/library/proxy/Meta/package.rds
/usr/lib64/R/library/proxy/Meta/vignette.rds
/usr/lib64/R/library/proxy/NAMESPACE
/usr/lib64/R/library/proxy/NEWS.Rd
/usr/lib64/R/library/proxy/R/proxy
/usr/lib64/R/library/proxy/R/proxy.rdb
/usr/lib64/R/library/proxy/R/proxy.rdx
/usr/lib64/R/library/proxy/doc/index.html
/usr/lib64/R/library/proxy/doc/overview.R
/usr/lib64/R/library/proxy/doc/overview.Rnw
/usr/lib64/R/library/proxy/doc/overview.pdf
/usr/lib64/R/library/proxy/help/AnIndex
/usr/lib64/R/library/proxy/help/aliases.rds
/usr/lib64/R/library/proxy/help/paths.rds
/usr/lib64/R/library/proxy/help/proxy.rdb
/usr/lib64/R/library/proxy/help/proxy.rdx
/usr/lib64/R/library/proxy/html/00Index.html
/usr/lib64/R/library/proxy/html/R.css
/usr/lib64/R/library/proxy/tests/apply.R
/usr/lib64/R/library/proxy/tests/apply.Rout.save
/usr/lib64/R/library/proxy/tests/distance.R
/usr/lib64/R/library/proxy/tests/distance.Rout.save
/usr/lib64/R/library/proxy/tests/distcalls.R
/usr/lib64/R/library/proxy/tests/distcalls.Rout.save
/usr/lib64/R/library/proxy/tests/registry.R
/usr/lib64/R/library/proxy/tests/registry.Rout.save
/usr/lib64/R/library/proxy/tests/util.R
/usr/lib64/R/library/proxy/tests/util.Rout.save

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/proxy/libs/proxy.so
/V4/usr/lib64/R/library/proxy/libs/proxy.so
/usr/lib64/R/library/proxy/libs/proxy.so
